<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL9RQN5Y\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL9RQN5Y/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL9RQN5Y.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL9RQN5Y\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerL9RQN5Y\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'L9RQN5Y',
    'container.build_id' => '0c6dda92',
    'container.build_time' => 1622208500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL9RQN5Y');
