<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerShyNiVX\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerShyNiVX/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerShyNiVX.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerShyNiVX\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerShyNiVX\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'ShyNiVX',
    'container.build_id' => '43279051',
    'container.build_time' => 1622469084,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerShyNiVX');
