<?php

// DO NOT EDIT! This file is auto generated by 'Shopware\Core\Framework\Feature'}
namespace Symfony\Component\DependencyInjection\Loader\Configurator;

return static function(ContainerConfigurator $configurator) {
    $configurator->parameters()->set(
        'shopware.features',
        array (
  'FEATURE_NEXT_1797' => false,
  'FEATURE_NEXT_11917' => false,
  'FEATURE_NEXT_12608' => true,
  'FEATURE_NEXT_13810' => false,
  'FEATURE_NEXT_6544' => false,
  'FEATURE_NEXT_15053' => false,
  'FEATURE_NEXT_14114' => false,
  'FEATURE_NEXT_12455' => false,
)
    );
};