<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7BUzORh\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7BUzORh/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7BUzORh.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7BUzORh\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \Container7BUzORh\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => '7BUzORh',
    'container.build_id' => '28230876',
    'container.build_time' => 1622189858,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7BUzORh');
